:root_path: ../..
include::{root_path}/adocs/_toc.adoc[]

= Design Patterns

== Summary
xref:_design_patterns_card.pdf[Design Patterns Card]

include::{root_path}/adocs/_to_index.adoc[]

== Design Patterns
[cols="^1,^2,<5,<2", %autowidth.stretch]
|===
^| Category ^| Pattern ^| Descriptions ^| Keywords

.5+| *Creational* 5
^| xref:creational/abstract_factory.adoc[Abstract Factory]
<a| * 제품군(재료) 생성
<| `Abstract`, `Create`

^| xref:creational/builder.adoc[Builder]
<a| * 객체의 생성 방법을 객체와 분리
<| `build`, `builder`, +
`생산자 오버로딩`

^| xref:creational/factory_method.adoc[Factory Method]
<a| * 구현 클래스에서 생성 기능 구현
<| -

^| xref:creational/prototype.adoc[Prototype]
<a| * 프로토타입 인스턴스로부터 `복제(clone)`
<| `clone`

^| xref:creational/singleton.adoc[Singleton]
<a| * 인스턴스를 하나만 생성
<| `instance`, `getInstance`

//-------------------------------------

.7+| *Structural* 7
^| xref:structural/adapter.adoc[Adapter]
<a| * 인터페이스 형태 적응(변환)
<| `Adapter`, `Adaptee`

^| xref:structural/bridge.adoc[Bridge]
<a| * 기능을 정의하는 클래스(모체)와 (기능)구현 클래스를 분리
<| `Abstraction`, `Implementor`, `RefineMethod`

^| xref:structural/composite.adoc[Composite]
<a| * 전체-부분 패턴, 단일 객체와 복합 객체 모두 동일한 인테페이스
<| `전체`, `부분`, `Component`, `Composite`, `recursive`

^| xref:structural/decorator.adoc[Decorator]
<a| * 동적으로 새로운 기능 추가
<| `Component 와 Decorator 의 Interface 가 같다.`

^| xref:structural/facade.adoc[Facade]
<a| * 복잡한 기능을 모아 간략화된 인터페이스 제공
<| `간략한 인터페이스`, `절차`

^| xref:structural/flyweight.adoc[Flyweight]
<a| * 가상 인스턴스 제공. 생성된 객체를 저장 후 재활용
<| `데이터공유`, `상태저장`, `가상 인스턴스`, `재사용`

^| xref:structural/proxy.adoc[Proxy]
<a| * 다른(내부) 객체에 대한 접근을 제어
<| -

//-------------------------------------

.11+| *Behavioral* 11
^| xref:behavioral/chain_of_responsibility.adoc[Chain of Responsibility]
<a| * 연속된 기능 클래스가 각자 자신이 처리할 수 있는 요청만 처리
 * eg> Spring Security Filter Chain
<| `next`

^| xref:behavioral/command.adoc[Command]
<a| * 요청을 객체로 캡슐화, 요청에 기능 추가
<| `Invoker`, `Command`, `Receiver`, `Client`

^| xref:behavioral/interpreter.adoc[Interpreter]
<a| * 구문을 특정한 문법으로 해석
<| -

^| xref:behavioral/iterator.adoc[Interator]
<a| * 저장소(데이터)와 순차 접근 방법을 분리
<| `Aggreate`, `next`, `hasNext`

^| xref:behavioral/mediator.adoc[Mediator]
<a| * 중간객체(Mediator)가 여러 객체들의 상호작용 간략화
<| `Colleague`, `상호관계`, `상호작용`

^| xref:behavioral/memento.adoc[Memento]
<a| * 상태 정보를 저장
<| `rollback`, `undo`

^| xref:behavioral/observer.adoc[Observer]
<a| * 객체의 상태가 변할 때 다른 객체들에게 변화를 통지
<| `notify`, `update`

^| xref:behavioral/state.adoc[State]
<a| * 각 상태에 대응하는 별도의 클래스를 만들어 상태 전이 로직 처리
<| `Context`, `State`

^| xref:behavioral/strategy.adoc[Strategy]
<a| * 동적 알고리즘 변경
<| `Algorithm`

^| xref:behavioral/template_method.adoc[Template Method]
<a| * Template Method 에서 abstract method 의 조합(절차) 정의
<|

^| xref:behavioral/visitor.adoc[Visitor]
<a| * 객체의 각 원소에 대해 수행할 기능을 분리
<| `Accept`
|===

include::{root_path}/adocs/_to_index.adoc[]

== Design patterns comparison

[cols="^2,<8", %autowidth.stretch]
|===
^| Pattern ^| 특징

| Abstract Factory  a| * 제품군(부품) 생성
| Builder           a| * Constructor Overloading 재정의
* 구축(Build) 방법이 구죽 대상(Product)과 분리
| Factory Method    a| * 하위(구현) 클래스에서 생성
|===

[cols="^2,<8", %autowidth.stretch]
|===
^| Pattern ^| 특징

| Proxy         a| * (내부의) 다른 객체를 숨김
| Decorator     a| * 다른 객체에 기능을 추가
| Adapter       a| * (내부) 객체의 인터페이스를 변경
| Facade        a| * (내부의) 여러 객체의 복잡한 기능을 모아, 보다 단순한 인터페이스로 변경
| Bridge        a| * 기능과 구현 분리
| Mediator      a| * 여러 객체간 커뮤니케이션 채널 단순화
|===

[cols="^2,<8", %autowidth.stretch]
|===
^| Pattern ^| 특징

| Facade            a| * (내부의) 여러 객체의 복잡한 기능을 모아, 보다 단순한 인터페이스로 변경
| Template Method   a| * (내부) Method 의 조합을 정의(Template Method).
* (내부) Method 의 동작은 구현 클래스에서 정의
|===

include::{root_path}/adocs/_to_index.adoc[]