:root_dir: ../../
:parent_dir: ../
include::{root_dir}/adocs/_toc.adoc[]

= Design Patterns

[cols="^1,^2,<5,<2", %autowidth.stretch]
|===
^| Category ^| Pattern ^| Descriptions ^| Keywords

.5+| *Creational* 5
^| xref:abstract_factory.adoc[Abstract Factory]
<a| * 서로 관련성이 있는 다양한 객체(재료)를 생성하기 위한 인터페이스를 제공한다.
<| `Abstract`, `Create`

^| xref:builder.adoc[Builder]
<a| * 객체의 생성 방법과 표현 방법을 분리한다.
<| `build`, `builder`, +
`생산자 오버로딩`

^| xref:factory_method.adoc[Factory Method]
<a| * 객체를 생성하기 위한 Method 의 인터페이스를 정의하고,
* 인스턴스 생성은 서브클래스가 결정하게 한다.
<| -

^| xref:prototype.adoc[Prototype]
<a| * 생성할 객체들의 타입이 프로토타입인 인스턴스로부터 결정되도록 하며,
* 인스턴스는 새 객체를 만들기 위해 자신을 `복제(clone)` 한다.
<| `clone`

^| xref:singleton.adoc[Singleton]
<a| * 인스턴스를 하나만 만들어 사용하기 위한 패턴이다.
<| `instance`, `getInstance`

//-------------------------------------

.7+| *Structural* 7
^| xref:adapter.adoc[Adapter]
<a| * 클래스의 인터페이스를 사용자가 기대하는 인터페이스 형태로 적응(변환) 시킵니다.
<| `Adapter`, `Adaptee`

^| xref:bridge.adoc[Bridge]
<a| * 기능을 정의하는 클래스와 (기능)구현 클래스를 분리 하는 패턴.
<| `Abstraction`, `Implementor`, `RefineMethod`

^| xref:composite.adoc[Composite]
<a| * 전체-부분 패턴, 단일 객체와 복합 객체 모두 동일하게 처리.
<| `전체`, `부분`, `Component`, `Composite`, `recursive`

^| xref:decorator.adoc[Decorator]
<a| * 객체에 동적으로 새로운 책임을 추가할 수 있게 합니다.
 * 서브클래스를 생성하는 것보다 융통성 있는 방법을 제공합니다.
<| `Component 와 Decorator 의 Interface 가 같다.`

^| Abstract Factory
<a| asdfasdf
<| adsfadsfasdf

^| Abstract Factory
<a| asdfasdf
<| adsfadsfasdf

^| Abstract Factory
<a| asdfasdf
<| adsfadsfasdf

//-------------------------------------

.11+| *Behavioral* 11
^| Abstract Factory
<a| asdfasdf
<| adsfadsfasdf
|===